package com.broker.retry;

public enum InternalRetryOperation {
    PRODUCT_CREATE,
    ORDER_CREATE,
    ORDER_UPDATE_PRODUCTS,
    ORDER_UPDATE_STATUS,
    PAYMENT_CREATE,
    PAYMENT_RECEIVED_EVENT,
    INVENTORY_UPDATE_EVENT,
    ORDER_STATUS_CHANGED_EVENT,
    EMAIL_NOTIFICATION_EVENT
}